version: '3.8'

services:
  dspaces:
    container_name: demo-dspaces
    image: philipdavis/dspaces:dspaces-run-upd-2
    environment:
      - DSPACES_DEBUG=1
      - OFI_STRING=sockets://eth0:4000
      - REPO_BRANCH=netcdf
    ports:
      - "4000:4000"
    networks:
      - backend

  demo:
    container_name: demo
    image: philipdavis/dspaces-demo
    ports:
      - "8888:8888"
    networks:
      - backend
    depends_on:
      - dspaces
    command: 
      - bash
      - -c
      - |
        export DSPACES_IP=$(/util/get_dspaces_ip.sh)
        export DSPACES_PORT=4000
        jupyter-lab --ip=$(/util/get_ip.sh) --config=/config/jupyter_server_config.json
    volumes:
      - ./util:/util
      - ./notebooks:/notebooks
      - ./config:/config
networks:
  backend:
    name: backend
    driver: bridge
